package Exceptionhandling;

public class Catch {

	public static void main(String[] args) {
		
		try
		{
			int result =5/0;
		}
	/*	catch (ArithmeticException e)
		{
			System.out.println("There is an exception");
		}*/
		
		finally
		{
			System.out.println("balance");
		}
	}

}
